# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=False)),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('is_system', models.BooleanField(default=False)),
                ('system_image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='/Users/dst/Code/Python/cirujanos/static_media/static/images/home/posts/default.jpg', upload_to='images/home/posts/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'sliders',
                'verbose_name': 'slider',
            },
        ),
    ]
