language: python
python:
  - 3.5
env:
  - DJANGO=1.10.4 DB=mysql
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements-devel.txt
  - npm install -g bower
  - npm install coffee-script
before_script:
  - mysql -e 'create database cirujanos_development;'
  - ./bin/setup_travis.sh
  - make setup
script:
  coverage run -m py.test -v --tb=native
after_success:
  coveralls
addons:
  sauce_connect: true
