language: python
python:
  - "2.7"
env:
  - DJANGO=1.6 DB=mysql
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q . --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
  - pip install coveralls
script:
  coverage run --source='.' python manage.py test cirujanos --liverserver=0.0.0.0:8081
  coverage report
after_success:
  coveralls
