language: python
python:
  - 2.7
env:
  - DJANGO=1.6 DB=mysql
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'create database cirujanos_development;'
script:
  coverage run --source='.' manage.py test cirujanos
after_success:
  coveralls
