language: python
python:
  - "2.7"
env:
  - DJANGO=1.6 DB=mysql
install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source='.' python manage.py test cirujanos
  coverage report
after_success:
  coveralls
