# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100)),
                ('param_value', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
