# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 11:52
from __future__ import unicode_literals

import cirujanos.apps.media.extensions
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('file', models.FileField(upload_to='articles')),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'articles',
                'verbose_name': 'article',
            },
            bases=(models.Model, cirujanos.apps.media.extensions.Publication),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='events')),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'events',
                'verbose_name': 'event',
            },
            bases=(models.Model, cirujanos.apps.media.extensions.Publication),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='articles')),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'slides',
                'verbose_name': 'slide',
            },
            bases=(models.Model, cirujanos.apps.media.extensions.Publication),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'videos',
                'verbose_name': 'video',
            },
            bases=(models.Model, cirujanos.apps.media.extensions.Publication),
        ),
    ]
