# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 11:52
from __future__ import unicode_literals

import cirujanos.apps.about.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'doctors',
                'verbose_name': 'doctor',
            },
            bases=(cirujanos.apps.about.models.DoctorDecorator, models.Model),
        ),
        migrations.CreateModel(
            name='DoctorContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_preview', tinymce.models.HTMLField()),
                ('content_details', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'doctorcontents',
                'verbose_name': 'doctorcontent',
            },
            bases=(cirujanos.apps.about.models.DoctorContentDecorator, models.Model),
        ),
        migrations.CreateModel(
            name='DoctorContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'doctorcontenttypes',
                'verbose_name': 'doctorcontenttype',
            },
        ),
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'contact notification receivers',
                'verbose_name': 'contact notification receiver',
            },
        ),
        migrations.AddField(
            model_name='doctorcontent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.DoctorContentType'),
        ),
        migrations.AddField(
            model_name='doctorcontent',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Doctor'),
        ),
    ]
